app1/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('guest', views.index_guest, name="guest")
]

app2/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name="index"),
    path('add-blog/', views.add_blog, name="add_blog"),
    path('details/<str:title>/', views.blog_content, name="blog_content"),
    path('details/<str:title>/like/', views.blog_like, name="like"),
    path('details/<str:title>/add-comment/', views.add_comment, name="add_comment")
]

project1ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from app1.views import login, logout, register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('blogs/', include('app2.urls')),
    path('about/', include('app3.urls')),
    path('recommendation/', include('app4.urls')),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
]

app2/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Visitor(models.Model):
    name = models.CharField(default="-", max_length=100)

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(default="-", max_length=100)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(Author, related_name="author_blogs", on_delete=models.CASCADE, null=True, blank=True)
    likes = models.ManyToManyField(Visitor, related_name="blog_likes", blank=True)

    def __str__(self):
        return self.title

    def blogTotalLikes(self):
        return self.likes.all().count()

    def blogTotalComments(self):
        return self.blog_comments.all().count()

class Comment(models.Model):
    message = models.CharField(max_length=500, null=True)
    commenter = models.ForeignKey(Visitor, related_name="visitor_comment", on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateField(auto_now=True)
    blog_commented = models.ForeignKey(Blog, related_name="blog_comments", on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "{} - {}".format(self.commenter, self.message)

app2/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content']

        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control', 'id': 'blog-title', 'placeholder': "Your blog's title"}),
            'content' : forms.Textarea(attrs={'class': 'form-control', 'id': 'blog-content', 'placeholder': "Your story..."}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

        widgets = {
            'message' : forms.Textarea(attrs={'class': 'form-control', 'id': 'blog-comment', 'placeholder': "Your comment..."}),
        }

app2/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.contrib.auth.models import User
from django.http import JsonResponse
import json

# Create your views here.


def index(request):
	blogs = Blog.objects.all()
	form = BlogForm()
	return render(request, 'app2/blog.html', {'blogs': blogs, 'form': form})

def add_blog(request):
	if request.method == "POST":

		title = request.POST.get('title')
		content = request.POST.get('content')

	
		visitor, created = Visitor.objects.get_or_create(name=request.user)

		author, created = Author.objects.get_or_create(name=request.user)

		newBlog = Blog.objects.create(title=title, content=content, author=author)

		listBlog = { blog.id : [blog.title, blog.content, blog.author.name] for blog in Blog.objects.all() }

		dictBlog = json.loads(json.dumps({'dataBlog' : [listBlog]}))

		return JsonResponse(dictBlog, safe=False)

def blog_content(request, title):
	blogs = Blog.objects.all()
		
	blog = Blog.objects.get(title=title)
	comment_form = CommentForm()

	visitor, created = Visitor.objects.get_or_create(name=request.user)

	if blog.likes.filter(name=visitor).exists():
		liked = True

	else:
		liked = False

	# if request.method == "POST":
		
	# 	comment_form = CommentForm(request.POST)
	# 	if comment_form.is_valid():
	# 		dataComment = comment_form.cleaned_data
	# 		msg = dataComment['message']
	# 		if request.COOKIES.get('name') == None:
	# 			prsn = "Anonymous"
	# 		else:
	# 		 	prsn = request.COOKIES.get('name')
	# 		blog.comment.create(message=msg, commenter=request.user)
	# 		blog.save()
	# 		return redirect('/blogs/')
	
	context = {'blog': blog, 'cform': comment_form, "liked":liked}

	return render(request, 'app2/blog_content.html', context)

	

def add_comment(request, title):
	blog = Blog.objects.get(title=title)
	if request.method == 'POST':
		comment = request.POST.get('comment')
		
		visitor, created = Visitor.objects.get_or_create(name=request.user)

		newComment = Comment.objects.create(message=comment, commenter=visitor, blog_commented=blog)

		listComment = { comment.id : [comment.message, comment.commenter.name, comment.date_created.strftime("%b %d, %Y")] for comment in blog.blog_comments.all() }

		dictComment = json.loads(json.dumps({'dataComment' : [listComment]}))
		
		return JsonResponse(dictComment, safe=False)
		# return JsonResponse(dictComment, safe=False)

def blog_like(request, title):
	blog = Blog.objects.get(title=title)
	
	if request.method == "POST":
		blog_id = request.POST.get('blog_id')

		visitor, created = Visitor.objects.get_or_create(name=request.user)

		if blog.likes.filter(name=visitor).exists():
			blog.likes.remove(visitor)
			liked = False
			
		else:
			blog.likes.add(visitor)
			liked = True
			
		listLiked = { blog_id : [visitor.name] for visitor in blog.likes.all() }
		# print(listLiked)
		visitorLiked = { 'liked' : liked }
		# print(visitorLiked)
		dictLiked = json.loads(json.dumps({'dataLiked' : [listLiked, visitorLiked]}))

		return JsonResponse(dictLiked, safe=False)

app2/templates/app2/blog.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Blogs
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_blog.css' %}">
{% endblock %}


{% block content %}
<div class="container-lg intros">
    <div class="intro">
        <img src="{% static 'admin/img/blog 1.svg' %}" alt="blog-icon">
        <h1 class="intro-title">Blogs.</h1>
        <p class="intro-subtitle">things you might want to know <br>about <span>quarantine</span> and such.</p>
    </div>
</div>

{% include 'app2/blog_form.html' %}


<div class="container-lg blog-intro-msg">
    <div class="blog-warn">
        {% if not blogs %}
        <h1>There are <span class="bold-red">no blogs</span> to be found so far. Add yours!</h1>
        {% else %}
        <h1 class="our-story">Here's <span class="bold-red">our story.</span> By <span class="bold-red">yours.</span></h1>
        {% endif %}
    </div>
</div>

<div class="container-fl blog-preview">
    <div class="row list-blog">
        {% for blog in blogs %}
            <div class="col-lg-4 d-flex align-items-stretch">
                <div class="card h-100 w-100">
                    <h3 class="card-title h-100">{{blog.title}}</h3>
                    <p class="card-text h-100">{{blog.content|truncatewords:15}}</p>
                    <div class="blog-info-count">
                        <div class="blog-likes">
                            <img src="https://www.flaticon.com/svg/static/icons/svg/1000/1000621.svg" alt="total-likes">
                            <h4 class="like-counter">
                                {{blog.blogTotalLikes}}
                            </h4>
                        </div>
                        <div class="blog-comments">
                            <img src="https://www.flaticon.com/svg/static/icons/svg/1380/1380338.svg" alt="total-likes">
                            <h4 class="comment-counter">
                                {{blog.blogTotalComments}}
                            </h4>
                        </div>
                    </div>
                    <div class="button-more">
                        <a class="btn btn-lg" href="{% url 'blogs:blog_content' blog.title %}" role="button">More</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block js %}
<script src="{% static 'admin/js/blog.js' %}"></script>
{% endblock %}

app2/templates/app2/blog_content.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
Blogs
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_blog.css' %}">
{% endblock %}

{% block content %}
<div class="container-lg blog-content">
    <div class="blog-about">
        <div class="blog-info">
            <h1 class="title">{{blog.title}}</h1>
            <h2 class="subtitle">By:<br>{{blog.author}}</h2>
        </div>
    </div>
    <p class="long-par">{{blog.content}}</p>
    
    <div class="blog-likes">
        {% if user.is_authenticated %}
        <form action="#" method="POST" id=like-submit name="{{blog.id}}" url_path="{% url 'blogs:like' blog.title %}">
            {% csrf_token %}
            {% if liked %}
            <input class="like-btn" id="like-btn" type="image" src="https://www.flaticon.com/svg/static/icons/svg/535/535183.svg" alt="Like">
            {% else %}
            <input class="like-btn" id="like-btn" type="image" src="https://www.flaticon.com/svg/static/icons/svg/1000/1000621.svg" alt="Unlike">
            {% endif %}
            <h3 class="like-counter">{{blog.blogTotalLikes}}</h3>
        </form>
        {% else %}
        <fieldset class="fieldset-disable-forms">
        <form action="#" method="POST" id=like-submit name="{{blog.id}}" url_path="{% url 'blogs:like' blog.title %}">
            {% csrf_token %}
            {% if liked %}
            <input class="like-btn" id="disabledlike-btn" type="image" src="https://www.flaticon.com/svg/static/icons/svg/535/535183.svg" alt="Like" disabled>
            {% else %}
            <input class="like-btn" id="disabledlike-btn" type="image" src="https://www.flaticon.com/svg/static/icons/svg/1000/1000621.svg" alt="Unlike" disabled>
            {% endif %}
            <h3 class="like-counter">{{blog.blogTotalLikes}}</h3>
        </form>
        </fieldset>
        <div class="alert alert-danger disabled-like-warn" role="alert">
            <h5>Sorry, you have to log in to use this feature. Log in <a href="{% url 'home:index' %}" class="alert-link" style="font-size: inherit;">here.</a></h5>
        </div>
        {% endif %}
    </div>
    
    
</div>

<div class="container-lg blog-comment">
    <div class="list-comment">
        <h1><span class="bold-red">comments</span></h1>
        <div class="each-comment">
            {% for com in blog.blog_comments.all %}
            <div class="comment">
                <h3><span class="bold-red">{{com.commenter}}</span> - ({{com.date_created}})</h3>
                <p class="long-par">{{com.message}}</p>
            </div>
            {% endfor %}
        </div>        
    </div>
    
    <div class="comment-form">
        <div class="intro-msg-comment">
            {% if blog.blog_comments.all %}
            <h1>Add your comment <span class="bold-red">here!</span></h1>
            {% else %}
            <h1>There are <span class="bold-red">no comments</span> so far. Add <span class="bold-red">yours!</span></h1>
            {% endif %}
        </div>
        <div class="form-group">
            <form action="#" method="post" id="comment-form" url_path="{% url 'blogs:add_comment' blog.title %}">
            {% csrf_token %}
            {% if user.is_authenticated %}
            {{cform}}
            <div class="send-btn">
                <input class="btn btn-lg but-add" type="submit" value="Send">
            </div>
            {% else %}
            <fieldset class="fieldset-disable-forms">
                {{cform}}
                <div class="send-btn">
                    <input class="btn btn-lg but-add" type="submit" value="Send" disabled>
                </div>
                <div class="alert alert-danger" role="alert">
                    <h5>Sorry, you have to log in to use this feature. Log in <a href="{% url 'home:index' %}" class="alert-link" style="font-size: inherit;">here.</a></h5>
                </div>
            </fieldset>
            {% endif %}
            </form>
            <div class="success-comment"></div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="{% static 'admin/js/blog.js' %}"></script>
<!-- <script src="{% static 'admin/js/blog.js' %}"></script> -->
{% endblock %}

app2/templates/app2/blog_form.html
<div class="container-lg blog-form polos">
    {% if name %}
    <h1>Hi {{name}}, tell us about <span class="bold-red">your story.</span></h1>
    {% elif user.is_authenticated %}
    <h1>Hi {{request.user.first_name}}, tell us about <span class="bold-red">your story.</span></h1>
    {% endif %}
    <div class="form-group">
        <form action="" method="POST" id="blog-form" url_path="{% url 'blogs:add_blog' %}">
        {% csrf_token %}
        {% if user.is_authenticated %}
        {{form}}
        <div class="send-btn">
            <input class="btn btn-lg but-add" type="submit" value="Send">
        </div>
        {% else %}
        <fieldset class="fieldset-disable-forms">
            {{form}}
            <div class="send-btn">
                <input class="btn btn-lg but-add" type="submit" value="Send" disabled>
            </div>
            <div class="alert alert-danger" role="alert">
                <h5>Sorry, you have to log in to use this feature. Log in <a href="{% url 'home:index' %}" class="alert-link" style="font-size: inherit;">here.</a></h5>
            </div>
        </fieldset>
        {% endif %}
        </form>
        <div class="success-blog"></div>
    </div>
    
</div>