app1/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('guest', views.index_guest, name="guest")
]

app2/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name="index"),
    path('add-blog/', views.add_blog, name="add_blog"),
    path('details/<str:title>/', views.blog_content, name="blog_content"),
    path('details/<str:title>/like/', views.blog_like, name="like"),
    path('details/<str:title>/add-comment/', views.add_comment, name="add_comment")
]

app3/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.index, name="index"),
    path('feedbackProcess/', views.feedbackProcess, name="feedbackProcess")
]

app4/urls.py
from django.urls import path
from . import views

app_name = 'recommendation'

urlpatterns = [
    path('', views.index, name="index"),
    path('games/', views.games, name="games"),
    path('movies/', views.movies, name="movies"),
    path('music/', views.music, name="music"),
    path('podcast/', views.podcast, name="podcast"),
    path('<str:model>/poll', views.poll, name="poll"),
]

project1ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from app1.views import login, logout, register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('blogs/', include('app2.urls')),
    path('about/', include('app3.urls')),
    path('recommendation/', include('app4.urls')),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Layout -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Tambahan CSS -->
    <link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/header_footer.css' %}">
    {% block css %}

    {% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-dark shadow-sm py-3">
            <div class="container">
                <div class="user_name">
                    <h4 style="color: aliceblue;">
                        {% if user.first_name %}
                        Hello, {{ user.first_name }}
                        {% elif request.session.name %}
                        Hello, {{ request.session.name }}
                        {% endif %}
                    </h4>
                </div>
                <a class="navbar-brand" href="/"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'home:index' %}">home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'about:index' %}">about</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'blogs:index' %}">blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'recommendation:index' %}">recommendation</a>
                        </li>
                        <!--<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'recommendation:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            recommendation
                        </a>-->
                        
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}
    
    {% endblock content %}


<!-- Footer -->

    <footer class="page-footer font-small">
      <!-- Copyright -->
      <div class="footer-copyright text-right py-3">
        <div class="footer-content">
            <div class="top" id="backtop">
                <a id="backtop_logo" href="#" onclick="scrollTopAnimated()">
                    <img src="{% static 'admin/img/icon (1).svg' %}" alt="icon-arrow">
                </a>
                <a id="backtop_text" href="#" onclick="scrollTopAnimated()"><p>back to top</p></a>
            </div>
            
            <p>© Copyright All right reserved |<a> Design by WETZ</a></p>
        </div>
        
      </div>    
      <!-- Copyright -->

    </footer>
    <!-- Footer -->


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"> </script> 
    <script type="text/javascript"> 
        function scrollTopAnimated() { 
            $("html, body").animate( 
                { scrollTop: "0" }, 700); 
        } 
    </script>
    
    {% block js %}

    {% endblock js %}
  
</body>
</html>

templates/base_kosong.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Layout -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <!-- Tambahan CSS -->
    <link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/header_footer.css' %}">
    {% block css %}
    
    {% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}
    
    {% endblock content %}


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    
    {% block js %}

    {% endblock js %}
  
</body>
</html>

templates/base_nofooter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Layout -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Tambahan CSS -->
    <link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/header_footer.css' %}">
    {% block css %}

    {% endblock css %}

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-dark shadow-sm py-3"> 
            
            <div class="container">
                <div class="user_name">
                    <h4 style="color: aliceblue;">
                        {% if user.first_name %}
                        Hello, {{ user.first_name }}
                        {% elif request.session.name %}
                        Hello, {{ request.session.name }}
                        {% endif %}
                    </h4>
                </div>
                <a class="navbar-brand" href="/"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'home:index' %}">home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'about:index' %}">about</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'blogs:index' %}">blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link scroll-link" href="{% url 'recommendation:index' %}">recommendation</a>
                        </li>
                        <!--<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'recommendation:index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            recommendation
                        </a>-->
                        
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block content %}
    
    {% endblock content %}


    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    
    {% block js %}

    {% endblock js %}
  
</body>
</html>

templates/home.html
{% extends 'base_kosong.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/homep.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/homepage_respons.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_login_register.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/sidebarnews.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/sidebar_responsives.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js%22%3E"></script>
{% endblock css %}


{% block title %}Homepage{% endblock title %}

{% block content %}
  <div aria-live="polite" aria-atomic="true">
    <div class="toast" style="position: absolute; top: 0; right: 0;" data-autohide="false">
      <div class="toast-header">
        <svg class="rounded mr-2" width="20" height="20" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice"
          focusable="false" role="img">
          <rect fill="#007aff" width="100%" height="100%" /></svg>
        <strong class="mr-auto">Notification</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body">
        {{msg}}
      </div>
    </div>
  </div>






{% if user.is_authenticated %}

<div id="mySidebar" class="sidebar">
	<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
  <!-- The sidebar -->
  {% comment %} <div class="row home">
  <div class="sidebar"> {% endcomment %}
	  <a href="{% url 'about:index' %}" class="icon">
		  <img src="{% static 'admin/img/Group_home.svg' %}" alt="console-icon" >
	  </a>
	  <a href="{% url 'blogs:index' %}" class="icon">
		  <img src="{% static 'admin/img/blog 1_home.svg' %}" alt="console-icon" >
	  </a>
	  <a href="{% url 'recommendation:index' %}" class="icon">
		  <img src="{% static 'admin/img/checklist 1_home.svg' %}" alt="console-icon" >
	  </a>
  </div>
  
  <div id="main">
  <!-- Page content -->
	  <div class="container-fluid home ">
		  <button class="openbtn" onclick="openNav()">>>></button> 
		  <div class="row rapi">
			  <div class="col col-lg-7">
				  <div class="d-flex h-100">
					  <div class="text-left align-self-center pads">
						  <h5 class="red first"> Hello, {{user.first_name}}. </h5>
						  <h2 class="yellow second"> What to do during, </h2>
						  <h1 class="wellcom red left third"> QUARAN </h1>
						  <h1 class="wellcom red left"> TINE? </h1>
						  <p class="descrip yellow"> Got nothing to do at home? You are stuck on your mind? Got bored during your quarantine? <strong class="red" > Explore US! </strong> and we'll show you something fun</p>
						  <a class="btn btn-lg" href="/logout/">Log out</a>
					  </div>
				  </div>
			  </div>
			  <div class="col col-lg-5 p-0 m-0">
				  <img src="{% static 'admin/img/gify.gif' %}" class="dekstop pict">
			  </div> 
		  </div>
	  </div>
  </div>

{% elif name %}
<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
<!-- The sidebar -->
{% comment %} <div class="row home">
<div class="sidebar"> {% endcomment %}
	<a href="{% url 'about:index' %}" class="icon">
		<img src="{% static 'admin/img/Group_home.svg' %}" alt="console-icon" >
	</a>
	<a href="{% url 'blogs:index' %}" class="icon">
		<img src="{% static 'admin/img/blog 1_home.svg' %}" alt="console-icon" >
	</a>
	<a href="{% url 'recommendation:index' %}" class="icon">
		<img src="{% static 'admin/img/checklist 1_home.svg' %}" alt="console-icon" >
	</a>
</div>

<div id="main">
<!-- Page content -->
	<div class="container-fluid home ">
		<button class="openbtn" onclick="openNav()">>>></button> 
		<div class="row rapi">
			<div class="col col-lg-7">
				<div class="d-flex h-100">
					<div class="text-left align-self-center pads">
						<h5 class="red first"> Hello, {{name}}. </h5>
						<h2 class="yellow second"> What to do during, </h2>
						<h1 class="wellcom red left third"> QUARAN </h1>
						<h1 class="wellcom red left"> TINE? </h1>
						<p class="descrip yellow"> Got nothing to do at home? You are stuck on your mind? Got bored during your quarantine? <strong class="red" > Explore US! </strong> and we'll show you something fun</p>
						<a class="btn btn-lg" href="/logout/">Log out</a>
					</div>
				</div>
			</div>
			<div class="col col-lg-5 p-0 m-0">
				<img src="{% static 'admin/img/gify.gif' %}" class="dekstop pict">
			</div> 
		</div>
	</div>
</div>

{% else %}
<div class="container-xl login-register-body">
	<div class="blanket">
		<h1 span class="well">WELCOME!</h1>
		<h3>Welcome to our website, please login or register first.</h2>
		<div class="buttons">
			<button type="button" class="btn btn-primary register" data-toggle="modal" data-target="#registerModal">Register</button>
			<button type="button" class="btn btn-primary login" data-toggle="modal" data-target="#loginModal">Login</button>
		</div>
		<h3>Or you could login as <span class="log-guest"><a href="{% url 'home:guest' %}">guest.</a></span></h3>
	</div>
</div>

<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="registerModalLabel">Register</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           <form method="post" action="/register/" id="registerPeserta">
            {% csrf_token %}
            <div class="form-group">
              <label>Name :
                <input required name="name" id="name" type="text" class="textinput textInput form-control"/>
              </label>
              <label>Email :
                <input required name="email" id="email" type="email" class="textinput textInput form-control"/>
              </label>
            </div>
            <div class="form-group">
              <label>Password :
                <input required name="password" id="password" type="password" class="textinput textInput form-control"/>
              </label>
              <label>Confirm Password:
                <input required type="password" name="confirm_password" id="confirm_password" class="textinput textInput form-control"/>
              </label>
              <span id='message'></span>
            </div>
            <button type="submit" id="submit-register" class="btn btn-primary">Register</button>
          </form>
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
          <a type="button" class="btn btn-primary" id="registerPeserta">Register</a>
        </div> -->
      </div>
    </div>
  </div>

  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="registerModalLabel">Login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           <form method="post" action='/login/' id="registerPeserta">
            {% csrf_token %}
            <div class="form-group">
              <label>Email :
                <input required name="email" id="email" type="email" class="textinput textInput form-control"/>
              </label>
              <label>Password :
                <input required name="password" id="password" type="password" class="textinput textInput form-control"/>
              </label>
            </div>
            <button type="submit" id="submit-register" class="btn btn-primary">Login</button>
          </form>
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
          <a type="button" class="btn btn-primary" id="registerPeserta">Register</a>
        </div> -->
      </div>
    </div>
  </div>

<!-- <div class="container">
	<div class = "wrap">
		<div class="form-form-group col-md-12 title">
			<h1 span class="well">WELCOME!</h1>	
			<h2 span class="what">What's your name?</h2>
		</div>

		<form method="post">
		{% csrf_token %}
			<div class="form-row">
				<div class="form-group col-md-12">
				{{form.name}}
				</div>
			</div>
		<button type="submit" class="btn">Submit</button>
		</form>
	</div>
</div> -->

{% endif %}

{% endblock content %}

{% block js %}
<script>
$(document).ready(function(){
    $(".pict").mouseenter(function(){
      $(this).css("width", 550);
    });
    $(".pict").mouseleave(function(){
      $(this).css("width", 500);
    });
  });
</script>
<script src="{% static 'admin/js/login_register.js'%}"></script>
<script>
  {% if msg is not None %}
    $('.toast').toast('show');
  {% endif %}
</script>
<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "150px";
  document.getElementById("main").style.marginLeft = "150px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>  

{% endblock js %}

templates/home2.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/homepage.css' %}">
{% endblock css %}


{% block title %}Homepage{% endblock title %}

{% block content %}

{% if not cek %}
<div class="container">
	<div class="a">
		<div class="form-form-group col-md-12 title">
			<h1 span class="well">WELCOME!</h1>	
			<h2 span class="what">What's your name?</h2>
		</div>

		<form method="post">
		{% csrf_token %}
			<div class="form-row">
				<div class="form-group col-md-12">
				{{form.name}}
				</div>
			</div>
		<button type="submit" class="btn">Submit</button>
		</form>
	</div>
</div>
{% else %}
<div class="container">
	<h3>Hi {{name}}</h3>
</div>
{% endif %}

{% endblock content %}

{% block js %}

    
{% endblock js %}

templates/login_guest.html
{% extends 'base_kosong.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/homep.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/homepage_respons.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/style_login_register.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/sidebarnews.css' %}">
<link rel="stylesheet" href="{% static 'admin/css/sidebar_responsives.css' %}">
{% endblock css %}


{% block title %}Homepage{% endblock title %}

{% block content %}

<div class="container">
	<div class = "wrap">
		<div class="form-form-group col-md-12 title">
			<h1 span class="well">WELCOME!</h1>	
			<h2 span class="what">What's your name?</h2>
		</div>

		<form method="post">
		{% csrf_token %}
			<div class="form-row">
				<div class="form-group col-md-12">
				{{form.name}}
				</div>
			</div>
		<button type="submit" class="btn">Submit</button>
		</form>
	</div>
</div>


{% endblock content %}

{% block js %}
    
{% endblock js %}

templates/login_register.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

{% endblock css %}

{% block content %}

<div class="container-fluid">

  <div aria-live="polite" aria-atomic="true" style="position: relative; min-height: 200px;">
    <div class="toast" style="position: absolute; top: 0; right: 0;" data-autohide="false">
      <div class="toast-header">
        <svg class="rounded mr-2" width="20" height="20" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice"
          focusable="false" role="img">
          <rect fill="#007aff" width="100%" height="100%" /></svg>
        <strong class="mr-auto">Notification</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body">
        {{msg}}
      </div>
    </div>
  </div>

  
  <div class="container log-reg" style="margin-top: 2rem;">
    <td class="text-center">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#registerModal">Register</button>
    </td>
    <td class="text-center">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">Login</button>
    </td>
  </div>
  

  <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="registerModalLabel">Daftar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           <form method="post" action="/register/" id="registerPeserta">
            {% csrf_token %}
            <div class="form-group">
              <label>Name :
                <input required name="name" id="name" type="text" class="textinput textInput form-control"/>
              </label>
              <label>Email :
                <input required name="email" id="email" type="email" class="textinput textInput form-control"/>
              </label>
            </div>
            <div class="form-group">
              <label>Password :
                <input required name="password" id="password" type="password" class="textinput textInput form-control"/>
              </label>
              <label>Confirm Password:
                <input required type="password" name="confirm_password" id="confirm_password" class="textinput textInput form-control"/>
              </label>
              <span id='message'></span>
            </div>
            <button type="submit" id="submit-register" class="btn btn-primary">Register</button>
          </form>
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
          <a type="button" class="btn btn-primary" id="registerPeserta">Register</a>
        </div> -->
      </div>
    </div>
  </div>

  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="registerModalLabel">Login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           <form method="post" action='/login/' id="registerPeserta">
            {% csrf_token %}
            <div class="form-group">
              <label>Email :
                <input required name="email" id="email" type="email" class="textinput textInput form-control"/>
              </label>
              <label>Password :
                <input required name="password" id="password" type="password" class="textinput textInput form-control"/>
              </label>
            </div>
            <button type="submit" id="submit-register" class="btn btn-primary">Login</button>
          </form>
        </div>
        <!-- <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
          <a type="button" class="btn btn-primary" id="registerPeserta">Register</a>
        </div> -->
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block js %}
<script src="{% static 'admin/js/login_register.js'%}"></script>
<script>
  {% if msg is not None %}
    $('.toast').toast('show');
  {% endif %}
</script>

{% endblock js %}